"""empty message

Revision ID: 4bf7844c0fd9
Revises: 9b9c73e66b1f
Create Date: 2024-09-18 19:43:33.339030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf7844c0fd9'
down_revision = '9b9c73e66b1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example1', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('example2', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('example3', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('next_review', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('interval', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('repetitions', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ease_factor', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('review_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_reviewed', sa.DateTime(), nullable=True))
        batch_op.drop_index('ix_cards_example')
        batch_op.create_index(batch_op.f('ix_cards_example1'), ['example1'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_example2'), ['example2'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_example3'), ['example3'], unique=False)
        batch_op.drop_column('example')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('example', sa.VARCHAR(length=256), nullable=False))
        batch_op.drop_index(batch_op.f('ix_cards_example3'))
        batch_op.drop_index(batch_op.f('ix_cards_example2'))
        batch_op.drop_index(batch_op.f('ix_cards_example1'))
        batch_op.create_index('ix_cards_example', ['example'], unique=False)
        batch_op.drop_column('last_reviewed')
        batch_op.drop_column('review_count')
        batch_op.drop_column('ease_factor')
        batch_op.drop_column('repetitions')
        batch_op.drop_column('interval')
        batch_op.drop_column('next_review')
        batch_op.drop_column('example3')
        batch_op.drop_column('example2')
        batch_op.drop_column('example1')

    # ### end Alembic commands ###
