"""empty message

Revision ID: 9b9c73e66b1f
Revises: 
Create Date: 2024-09-17 14:52:47.054867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b9c73e66b1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verb', sa.String(length=64), nullable=False),
    sa.Column('meaning', sa.String(length=128), nullable=False),
    sa.Column('example', sa.String(length=256), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_example'), ['example'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_meaning'), ['meaning'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_verb'), ['verb'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_verb'))
        batch_op.drop_index(batch_op.f('ix_cards_meaning'))
        batch_op.drop_index(batch_op.f('ix_cards_example'))

    op.drop_table('cards')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
